# Generated by Django 4.2.5 on 2023-10-04 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Date_Time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='Image',
            field=models.FileField(null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='user',
            name='Last_Login_Date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='Last_Login_Time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='Message',
            field=models.TextField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='No_Of_Times_Login',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='Otp_Num',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='Otp_Status',
            field=models.TextField(default='pending', max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='User_Status',
            field=models.TextField(default='pending', max_length=50, null=True),
        ),
    ]
